# Tmux 3.1

# Unbinding prefix from C-b to C-a
set -g prefix C-a
unbind C-b

set -s escape-time 1

bind r source-file ~/.tmux.conf \; display "Reloaded"

bind C-a send-prefix

unbind C-S

bind | split-window -h

bind - split-window -v


bind  h select-pane -L
bind  j select-pane -D
bind  k select-pane -U
bind  l select-pane -R

bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

bind v copy-mode 

#setw -g mode-mouse off

setw -g monitor-activity on
set -g visual-activity on

setw -g mode-keys vi


set -g status-right-length 60

#set-window-option automatic-rename "on"

set -g status-right "#T : %d %b %R"

set -g base-index 1
setw -g pane-base-index 1


setw -g history-limit 4000

# default statusbar colors
set-option -g status-bg colour235 #base02
set-option -g status-fg colour136 #yellow



# pane number display
set-option -g display-panes-active-colour colour33 #blue
set-option -g display-panes-colour colour166 #orange

# clock
set-window-option -g clock-mode-colour colour64 #green

 set-option -sa terminal-features ',XXX:RGB'

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'


run '~/.tmux/plugins/tpm/tpm'
